file_format: "1"
id: zenFlow
name: zenFlow
type: shield
url: https://github.com/Aodrulez/zenFlow
requires: [pro_micro]
features:
  - keys
  - display
  - studio
siblings:
  - zenFlow_left
  - zenFlow_right
